export component Avatar {
    in property <image> source;
    in property <bool> is-circle;
    in property <brush> color;
    callback clicked();

    width: 50px;
    height: 50px;

    Rectangle {
        border-radius: is-circle ? self.width / 2 : 10px;
        background: #eee;

        Image {
            width: parent.width / 2;
            height: parent.height / 2;
            source: root.source;
            colorize: root.color;
        }

        TouchArea {
            mouse-cursor: pointer;
            clicked => {
                root.clicked();
            }
        }
    }
}