export component Input inherits Rectangle {
    property <bool> is-show: true;
    in property <string> place-holder-text: "Please input text";

    callback edited();
    callback accepted();
    callback leaved();

    width: 200px;
    height: 30px;
    background: #ffffff;
    border-radius: 5px;
    border-color: gray;
    border-width: 1px;
    clip: true;

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 5px;
        padding-bottom: 5px;

        text-input := TextInput {
            color: #000000;
            vertical-alignment: center;
            single-line: true;

            changed has-focus => {
                if self.has-focus {
                    root.border-color = Colors.blue;
                } else {
                    root.border-color = Colors.gray;

                    root.leaved();
                }
            }

            edited() => {
                root.is-show = text-input.text == "";
                root.edited();
            }

            accepted => {
                root.accepted();
            }
        }
    }

    if root.is-show : place-holder := Text {
        x: 10px;
        color: gray;
        text: root.place-holder-text;
    }
}