import { SInput, SRadio, SAvatar, SSlider, SSwitch } from "../slint-widgets/mod.slint";

export component App inherits Window {
    min-width: 600px;
    min-height: 600px;

    VerticalLayout {
        spacing: 20px;
        
        SInput {
            place-holder-text: "Enter your name";
            edited => {
                debug("Name edited");
            }
            accepted => {
                debug("Name accepted");
            }
            leaved => {
                debug("Name focus leave");
            }
        }

        SInput {
            place-holder-text: "Enter your email";
            edited => {
                debug("Edit email");
            }
        }

        SRadio {
            checked: true;
            text: "Option 1";
            clicked(value) => {
                debug("Clicked radio with text: " + value);
            }
        }

        SRadio {
            text: "Option 2";
            clicked(value) => {
                debug("Clicked radio with text: " + value);
            }
        }

        SAvatar {
            is-circle: true;
            source: @image-url("../assets/account.svg");
        }

        SAvatar {
            is-circle: false;
            source: @image-url("../assets/account.svg");
            color: Colors.purple;

            clicked => {
                debug("Avatar clicked");
            }
        }

        VerticalLayout {
            spacing: 20px;
            SSlider {
                value: 100;
                min: 50;
                max: 200;
                moved(value) => {
                    debug("Slider moved to value: " + value);
                }
                clicked(value) => {
                    debug("Slider clicked to value: " + value);
                }
            }
        }

        SSwitch {
            clicked(is-open) => {
                debug("Switch is now: " + (is-open ? "ON" : "OFF"));
            }
        }
    }
}